In [1]:
import numpy as np

In [2]:
np.array([[0.95, 0.29], [0.94, 0.001]])*0.7*0.9

array([[0.5985 , 0.1827 ],
       [0.5922 , 0.00063]])

In [3]:
np.array([[1-0.95, 1-0.29], [1-0.94, 1-0.001]])*0.05*0.01

array([[2.500e-05, 3.550e-04],
       [3.000e-05, 4.995e-04]])

In [4]:
np.array([[0.95, 0.29], [0.94, 0.001]])*0.7*0.9+np.array([[1-0.95, 1-0.29], [1-0.94, 1-0.001]])*0.05*0.01

array([[0.598525 , 0.183055 ],
       [0.59223  , 0.0011295]])

* P(J=T,M=T|B=T,E=T) = 0.598525
* P(J=T,M=T|B=F,E=T) = 0.183055
* P(J=T,M=T|B=T,E=F) = 0.59223
* P(J=T,M=T|B=F,E=F) = 0.0011295

Given P(E=T)=0.002 and P(E=F)=0.998, this product is actuay the marginalization and its result can be regarded as:
* P(E=T)P(J=T,M=T|B=T,E=T) + P(E=F)P(J=T,M=T|B=T,E=F) = P(J=T,M=T|B=T)
* P(E=T)P(J=T,M=T|B=F,E=T) + P(E=F)P(J=T,M=T|B=F,E=F) = P(J=T,M=T|B=F)

In [5]:
np.dot(np.array([0.002, 0.998]), np.array([[0.598525 , 0.183055 ],[0.59223  , 0.0011295]]))

array([0.59224259, 0.00149335])

* P(J=T,M=T|B=T) = 0.59224259
* P(J=T,M=T|B=F) = 0.00149335

In [6]:
np.dot(np.array([0.001, 0.999]), np.array([0.59224259, 0.00149335]))

0.0020840992399999998

Marginalization over B: P(J=T,M=T) = P(B=T)P(J=T,M=T|B=T)+P(B=F)P(J=T,M=T|B=F) = 0.0020840992399999998

In [7]:
1/0.0020840992399999998 * 0.001 * 0.59224259

0.2841719715803937

P(B=T|J=T,M=T) = 1/P(J=T,M=T) * P(J=T,M=T|B=T)P(B=T) = 0.2841719715803937