In [1]:
import numpy as np

In [2]:
np.array([[0.95, 0.29], [0.94, 0.001]])*0.7*0.9

array([[0.5985 , 0.1827 ],
       [0.5922 , 0.00063]])

In [3]:
np.array([[1-0.95, 1-0.29], [1-0.94, 1-0.001]])*0.05*0.01

array([[2.500e-05, 3.550e-04],
       [3.000e-05, 4.995e-04]])

In [4]:
np.array([[0.95, 0.29], [0.94, 0.001]])*0.7*0.9+np.array([[1-0.95, 1-0.29], [1-0.94, 1-0.001]])*0.05*0.01

array([[0.598525 , 0.183055 ],
       [0.59223  , 0.0011295]])

In [5]:
np.dot(np.array([0.002, 0.998]), np.array([[0.95, 0.29], [0.94, 0.001]])*0.7*0.9+np.array([[1-0.95, 1-0.29], [1-0.94, 1-0.001]])*0.05*0.01)

array([0.59224259, 0.00149335])

In [6]:
np.dot(np.array([0.001, 0.999]), np.array([0.59224259, 0.00149335]))

0.0020840992399999998

In [7]:
1/0.0020840992399999998 * 0.001 * 0.59224259

0.2841719715803937